project     = "some-project"
environment = "dev"
location    = "East US"
shortloc    = "eus"
storagename = "somestorage"
tagappname  = "SomeApp"
ownedby     = "Someone"
createdby   = "Michael Viggiani"
